DO $$ BEGIN
 CREATE TYPE "public"."goal_status" AS ENUM('진행전', '진행중', '완료', '보류');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."task_status" AS ENUM('대기', '진행중', '완료');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "air-base_goal" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "air-base_goal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text,
	"due_date" timestamp with time zone,
	"progress" integer DEFAULT 0,
	"status" "goal_status" DEFAULT '진행전' NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "air-base_task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "air-base_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text,
	"status" "task_status" DEFAULT '대기',
	"due_date" timestamp with time zone,
	"goal_id" integer NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "air-base_goal" ADD CONSTRAINT "air-base_goal_user_id_air-base_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."air-base_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "air-base_task" ADD CONSTRAINT "air-base_task_goal_id_air-base_goal_id_fk" FOREIGN KEY ("goal_id") REFERENCES "public"."air-base_goal"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "air-base_task" ADD CONSTRAINT "air-base_task_user_id_air-base_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."air-base_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "goal_user_id_idx" ON "air-base_goal" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "goal_title_idx" ON "air-base_goal" USING btree ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_goal_id_idx" ON "air-base_task" USING btree ("goal_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_user_id_idx" ON "air-base_task" USING btree ("user_id");